### ISSUE TITLE
Create a roadmap for the ODD SDK

### ISSUE THREAD

**Issue by bdehaynin** [oddsdk/ts-odd#543]
_Lists to be filled and discussed for the creation of the roadmap_

### Preliminary Questions
- What are our objectives for the next 6 months?
- What dependencies does the ODD SDK have?
  - Fission Server
  - rs-WNFS fearture parity on the old system
  - WASM
  - rs-UCAN
  - AWAKE
    - In what language are we going to implement AWAKE? (Rust or Typescript)
 
### Milestones 
_What are our next big increments/objectives?_
Some milestones already exist in the ts-odd repo, a cleanup is probably in order: 
- Integrate rs-WNFS - September 15
- Feature parity with stable branch - November 17
- App Accounts - TBD 
- Future Considerations
- Further milestones to be discussed

### Tasks to breakdown/do and prioritize
- [ ] https://github.com/oddsdk/ts-odd/issues/501
- [ ] https://github.com/oddsdk/ts-odd/issues/371
- [ ] [Standalone UCAN](https://github.com/oddsdk/ts-odd/milestone/7)
- [ ] [Transactional Semantics](https://github.com/oddsdk/ts-odd/milestone/5) (empty)
- [ ] [Webnative Marketing Release](https://github.com/oddsdk/ts-odd/milestone/9) (empty)

### Resources:
- [Starmap project issue](https://github.com/fission-codes/Fission-Starmap/issues/68)
- [Fission accounts on Figma](https://www.figma.com/file/YNR1XdOGkDNyGFPziQNIpY/Fission-Accounts?type=whiteboard&node-id=0-1&t=uD8JA7QEwvugfp5i-0)
